=head1 NAME

tablet-config - GNOME control center utility to configure graphics tablet devices

=head1 SYNOPSIS

B<tablet-config> S<[I<OPTION>]... [I<COMMAND>]>

=head1 DESCRIPTION

 The tablet-config utility allows you to select a different device
 and check what pressure and tilt information is being recieved from it. This
 dialog also contains a small drawing test area to give your pen a quick test.

=head1 AUTHORS

Alex Mac <alex@alexmac.cc>
Karl Ostmo <kostmo@gmail.com>
Thomas Iorns <mesilliac@gmail.com>
Juho Vepsala

=head1 REPORTING BUGS

Report bugs at http://groups.google.co.uk/group/alexmac
