install:
	mkdir -p /usr/share/pressure-applet
	cp pressure-applet.py /usr/bin/
	cp pressure-applet.server /usr/lib/bonobo/servers/
	mkdir -p /usr/share/tablet-capplet
	cp tablet-capplet.glade /usr/share/tablet-capplet/
	cp tablet-capplet.py /usr/bin/
	cp tablet-capplet.desktop /usr/share/applications/
clean:
	rm -f *~
