=head1 NAME

tablet-apps - Gnome panel and control center applets to configure and monitor graphics tablet devices

=head1 SYNOPSIS

tablet-apps

=head1 DESCRIPTION

B<TODO> Finish me.

=head1 BUGS

B<TODO> Finish me.

=head1 AUTHORS

B<tablet-apps> was written by Alex Mac <alex@alexmac.cc> with contributions from Juho Vepsäläin.

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2, or (at your option) any
later version.

On Debian GNU/Linux systems, the complete text of the GNU General
Public License can be found in `/usr/share/common-licenses/GPL'.

=cut
