=head1 NAME

tablet-pressure-applet - GNOME panel applet to monitor graphics tablet devices

=head1 SYNOPSIS

B<tablet-pressure-applet>

=head1 DESCRIPTION

 The GNOME Wacom applet is a small gnome panel applet that shows how much
 pressure is being applied to your wacom tablet by the current device. Clicking
 on the panel icon brings up the tablet-config dialog.

=head1 AUTHORS

Alex Mac <alex@alexmac.cc>
Karl Ostmo <kostmo@gmail.com>

=head1 BUGS

 The applet may not show up in the list of available GNOME panel applets right
 after installing.  This bug is known:
 http://bugs.launchpad.net/ubuntu/+source/gnome-panel/+bug/21625

=head1 REPORTING BUGS

Report bugs at http://groups.google.co.uk/group/alexmac
